### ISSUE TITLE
30 Videos on Joe edits wikipedia Channel and shown to friends

### ISSUE THREAD

**Issue by joereddington** [joereddington/Projects-Public#15]
I enjoy editing wikipedia and I'd like to make it 'offical' by doing some blogging and videoing and so on. 

The three things I'd like to do are: 
* Have 30 videos online with proper intro and outtros
   - [ ] Record videos 
   - [x] Record proper intro-outro
   - [  ] Get the intro-outro successfully added to the existing videos.
   - [ ] Reupload existing videos with proper intro-outro
* Have written a blog article about what I'm doing and why, and why it's public. 
* Have written the social media post and shared the videos. 

# Bonus 
* I'd also like to write some contributions code. That should be in a seperate issue #25 so it doesn't slow down this one.

**Comment by joereddington** [comment]
Okay, what do I need? 

The page I want to edit is this one: 

https://en.wikipedia.org/wiki/Special:Contributions/Joereddington

and I want to be able to do 2 things:
* Have a link from the contribution list to the videos
* Have a link in the description of the videos. 


Let's think about the design. 

Okay, If I had a list of URLs and their start time and a list of edits, then both parts are easy. Right? 

Okay, this is the JSON for contributions: 

https://en.wikipedia.org/w/api.php?action=query&format=json&list=usercontribs&ucuser=joereddington

I'd have to do the youtube one by hand. 

...this is where it talks about the API: 

https://www.mediawiki.org/wiki/API:Usercontribs

There's a complexity about 'only get's the last 500 edits' but that can be solved later.

**Comment by joereddington** [comment]
Use this: https://superuser.com/questions/138331/using-ffmpeg-to-cut-up-video  to put a front/back on each video.

**Comment by joereddington-public** [comment]
Today's project: professionalising the first 20 videos. 

I've created an intro file 

the program is : /opt/local/bin/ffmpeg 

I've created a folder to test .

Trying this: https://stackoverflow.com/questions/7333232/how-to-concatenate-two-mp4-files-using-ffmpeg

The 'fast' one gave black screen in the middle, currnetly trying the slow. 

Next thing to do is sort out the code around this. 

13:31,
The slow method is far too slo. 
 

  544  /opt/local/bin/ffmpeg -i Intro.mp4 -c copy -bsf:v h264_mp4toannexb -f mpegts episode1.ts
  545  /opt/local/bin/ffmpeg -i episode1.mp4 -c copy -bsf:v h264_mp4toannexb -f mpegts episode1.ts
  546  ls
  547  /opt/local/bin/ffmpeg -i outro.mp4 -c copy -bsf:v h264_mp4toannexb -f mpegts out.ts
  548  /opt/local/bin/ffmpeg -f mpegts -i "concat:intro.ts|episode1.ts|out.ts" -c copy -bsf:a aac_adtstoasc output.mp4
  549  ls
  550  open .
  551  /opt/local/bin/ffmpeg -f mpegts -i "concat:intro.ts|out.ts" -c copy -bsf:a aac_adtstoasc hope.mp4

 from https://trac.ffmpeg.org/wiki/Concatenate

**Comment by joereddington** [comment]
Have asked a question on stackoverflow https://webmasters.stackexchange.com/questions/123362/why-is-the-results-of-this-ffmpeg-command-blank

**Comment by joereddington-public** [comment]
Trying again.  Merging the last two videos (which should have the same codexs because they were produced by the same machine...)

**Comment by joereddington** [comment]
Sprint on this today.  

The command /opt/local/bin/ffmpeg -f concat -i input.txt -c copy output2.mp4
 from https://superuser.com/questions/1446436 appears to work but I lost the post2.mp4 connection on the last video I tried.  

Something is bothering me a lot about this. 

## 19/09/19 05:05 to 06:24, Working on [200~https://github.com/joereddington/projects-public/issues/15[201~ +PersonalProject
* Had to rewrite the issue - there was missing infomation for some reason. 
* Episode 1 is now fine
* Downloaded the next few episodes to work on. 
* Split the 'contriputions code' into a new issue 
* Something really bothering me about this. 


## 19/09/19 06:20 
Okay, so the thing I uploaded, it gg

Next actions: 
* Rewrite the issue 
* Download the next file and run the code on it. 
* Think about customthumbnails. 
* Do a brainstorm - something is really borthering me about this.

**Comment by joereddington** [comment]
Blogged on joereddington.com and I did a facebook post.
